// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"database/sql"
	"time"
)

type Account struct {
	AccountID int32
	Name      string
	Cpf       string
	Secret    string
	Balance   int32
	CreatedAt time.Time
}

type Transfer struct {
	TransferID         int32
	OriginAccount      sql.NullInt32
	DestinationAccount sql.NullInt32
	Amount             int32
	CreatedAt          time.Time
}
