// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package sqlc

import (
	"context"
	"time"
)

const insertAccount = `-- name: InsertAccount :one
INSERT INTO account(name, cpf, secret, balance, created_at) values($1, $2, $3, $4, $5) RETURNING account_id
`

type InsertAccountParams struct {
	Name      string
	Cpf       string
	Secret    string
	Balance   int32
	CreatedAt time.Time
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.Name,
		arg.Cpf,
		arg.Secret,
		arg.Balance,
		arg.CreatedAt,
	)
	var account_id int32
	err := row.Scan(&account_id)
	return account_id, err
}
